/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tungtung.gltf 
Author: Eks.Art (https://sketchfab.com/Eks.Art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tung-tung-tung-sahur-91ddd9079bd84019ba4a12e01d93a0d6
Title: Tung Tung Tung Sahur
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tungtung.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.model001_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={241.922} />
      </group>
    </group>
  )
}

useGLTF.preload('/tungtung.gltf')
